### ISSUE TITLE
Build doesnt work on MacOS Python3.8 

### ISSUE THREAD

**Issue by janwijbrand** [walkIT-nl/orthanc-server-extensions#29]
The underlying reasons seems to be setuptools tries to import `windows_support` when the package is build by tox. This fails on python3.8 on MacOS. Cannot find references to a know bug as of yet.

Demonstration:

```
jw@makker orthanc-server-extensions % python3.7 -c "from setuptools import windows_support"
```

```
jw@makker orthanc-server-extensions % python3.8 -c "from setuptools import windows_support"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so, 2): Symbol not found: __dyld_shared_cache_contains_path
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so
```

```
jw@makker orthanc-server-extensions % python3.9 -c "from setuptools import windows_support"
```

**Comment by janwijbrand** [comment]
Resolved: I used the wrong Python3.8.10 installer. See screenshot. The installer suitable for Big Sur doesnt work on Mojave.

<img width="1264" alt="isntaller" src="https://user-images.githubusercontent.com/530800/119969278-a4800480-bfae-11eb-9cdb-5e8a846f5cd6.png">
